### ISSUE TITLE
Croatian translation

### ISSUE THREAD

**Issue by milotype** [internetarchive/fatcat-scholar#23]
Please implement "Croatian" in the language menu and update translations from Weblate.

**Comment by bnewbold** [comment]
I rolled out Croatian as an option in the menu, and browser preferences should also be detected.

There are a couple periods after numbers ("."). I will make comments on weblate of these instances, but worth noting here is that the CSS for the filter sidebar is a little weird (swapped LTR mode), which results in the period ending up at the beginning of the term. If the periods are in fact expected and correct in a locale-specific way, I will need to figure out a different way to achieve the left-to-right alignment in CSS.

**Comment by bnewbold** [comment]
The periods do seem correct (apologies for my ignorance). I will close this issue, discussion of the display problem can continue in https://github.com/internetarchive/fatcat-scholar/issues/24.

Thank you @milotype for your work on this translation!
