### ISSUE TITLE
Fix periods (eg, for Croatian translation) in filter bar CSS (right-to-left)

### ISSUE THREAD

**Issue by bnewbold** [internetarchive/fatcat-scholar#24]
Currently, as sort of a hack, we use left-to-right mode for the filters sidebar, to right-justify text without wrapping.

This breaks display of, eg, Croatian numerals, which have a period after the number. In the current CSS, the period is displayed on the far left instead of just after the number as expected. This is presumably due to the RTL mode.

I think the fix will be to use different CSS to achieve right-justification. Will need to test the fix in a RTL language (eg, Arabic) before deploying.

**Comment by milotype** [comment]
Please note:
Croatian always uses a **period** after `date` and `year` values. For instance;:

`20. siječnja 2020.`

**Comment by milotype** [comment]
Yes, there is still  a problem with the period. See screenshot ... The period should be after the year ...

![Time-period](https://user-images.githubusercontent.com/43657314/99593291-bb3b1280-29f1-11eb-9f09-0c43c210c003.png)

**Comment by milotype** [comment]
Just to inform you, that the problem doesn't exist when the window size is changed to tablet or smaller sizes, as you don't use the rtl-direction style in that case.

![Tablet size](https://user-images.githubusercontent.com/43657314/99674073-d7809300-2a75-11eb-8d19-b3ffa37045a8.png)

**Comment by bnewbold** [comment]
This should be fixed now.
