### ISSUE TITLE
DBLP: "of" to "&" ?

### ISSUE THREAD

**Issue by rffontenelle** [internetarchive/fatcat-scholar#65]
https://github.com/internetarchive/fatcat-scholar/blob/cbbb5993f241cdc1afae73b31bc0a7304d3ae2d8/fatcat_scholar/templates/help.html#L226

Reading in [DBLP in Wikipedia](https://en.wikipedia.org/wiki/DBLP):

> DBLP originally stood for DataBase systems and Logic Programming. As a backronym, it has been taken to stand for Digital Bibliography & Library Project;[9] however, it is now preferred that the acronym be simply a name, hence the new title "The DBLP Computer Science Bibliography".[10] 

Should the `of` be replaced with `&amp;` to result in `&` ?

**Comment by bnewbold** [comment]
Thanks!
