### ISSUE TITLE
i18n/hr: 'Support and Acknowledgements' paragraph on About page not displaying translation (even though translation exists)

### ISSUE THREAD

**Issue by milotype** [internetarchive/fatcat-scholar#81]
For some reason the last paragraph **Support and Acknowledgements** at https://scholar-qa.archive.org/hr/about does not show in Croatian, allthough the strings are translated at Weblate (https://hosted.weblate.org/translate/internetarchive/fatcat-scholar/hr/?checksum=b661a6477d95136c&sort_by=-priority,position)

Also on the page https://scholar-qa.archive.org/hr/help there are headings **Tags** and **Persistent Identifiers** which do not translate and do not exist on Weblate.

**Comment by bnewbold** [comment]
Thanks for catching these!

The "Tags" and "Persistent Identifiers" were missing translation labels, I updated them and pushed to weblate.

I'm not exactly sure why the "Support and Acknowledgements" paragraph text is not displaying with translations. It might have to do with differing sensitivity to whitespace in different systems; weblate seems flexible and does fuzzy match, but the runtime system (babel) might not in this case. I pushed a small update to the `.pot` file which removes excess whitespace, that might fix it the next time `.po` files are generated and merged from weblate.

As a small note, the URLs above are to scholar-qa.archive.org, which is our testing instance, as opposed to scholar.archive.org. The testing instance isn't always in sync with development. I think that is why the "Support and Acknowledgements" title was not translated, but does not explain the body text.

**Comment by milotype** [comment]
Thank you for your answer. I updated Weblates Croatian strings … so we'll see what happens …

**Comment by bnewbold** [comment]
These have all been updated in weblate, merged to this repo, and deployed to both QA and production!

**Comment by milotype** [comment]
Works on both sites now … great!
